name: "HashComparativo (AR, main)"

concurrency:
  group: hashcomparativo-main
  cancel-in-progress: true

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install deps
        shell: bash
        run: |
          set -e
          python -m pip install --upgrade pip
          pip install requests openpyxl selenium webdriver-manager

      - name: Ensure dirs and placeholders
        shell: bash
        run: |
          set -e
          mkdir -p public_db public_listas public_reports assets _db/hash _db/snapshots downloads
          [ -f public_db/.gitkeep ]      || : > public_db/.gitkeep
          [ -f public_listas/.gitkeep ]  || : > public_listas/.gitkeep
          [ -f public_reports/.gitkeep ] || : > public_reports/.gitkeep
          [ -f public_listas/index.json ]  || echo "[]" > public_listas/index.json
          [ -f public_reports/index.json ] || echo "[]" > public_reports/index.json

      - name: Guard window AR
        id: guard
        shell: bash
        run: |
          set -e
          export TZ=America/Argentina/Buenos_Aires
          DOW=$(date +%u)
          H=$(date +%H)
          if [ "$DOW" -gt 5 ]; then echo "skip=true" >> "$GITHUB_OUTPUT"; exit 0; fi
          if [ "$H" -lt 7 ] || [ "$H" -ge 18 ]; then echo "skip=true" >> "$GITHUB_OUTPUT"; exit 0; fi
          echo "skip=false" >> "$GITHUB_OUTPUT"

      - name: Precheck metas are today (AR) for ALL sources
        id: precheck
        if: steps.guard.outputs.skip != 'true'
        shell: bash
        run: |
          set -e
          AR_TODAY=$(TZ=America/Argentina/Buenos_Aires date +%F)
          files=(public_db/Tevelam_DB.meta.json public_db/Disco_Pro_DB.meta.json public_db/ARS_Tech_DB.meta.json public_db/IMSA_DB.meta.json)
          all_exist=true
          for f in "${files[@]}"; do
            [ -f "$f" ] || all_exist=false
          done
          if [ "$all_exist" != true ]; then
            echo "skip=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          all_today=true
          for f in "${files[@]}"; do
            d=$(grep -o '"saved_at_ar"[[:space:]]*:[[:space:]]*"[0-9-]\{10\}' "$f" | head -n1 | sed 's/.*"\([0-9-]\{10\}\)$/\1/')
            [ "$d" = "$AR_TODAY" ] || all_today=false
          done
          if [ "$all_today" = true ]; then
            echo "skip=true" >> "$GITHUB_OUTPUT"
          else
            echo "skip=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Run script
        if: steps.guard.outputs.skip != 'true' && steps.precheck.outputs.skip != 'true'
        shell: bash
        env:
          WORKDIR: ${{ github.workspace }}
          IMSA_PASSWORD: ${{ secrets.IMSA_PASSWORD }}
          BORRAR_DUPLICADO: "true"
          IMSA_SOLO_CON_STOCK: "true"
        run: |
          set -e
          python hash_comparativo.py

      - name: List and commit
        if: steps.guard.outputs.skip != 'true' && steps.precheck.outputs.skip != 'true'
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git fetch origin main
          git add -A
          if git diff --cached --quiet; then
            echo "No changes."
            exit 0
          fi
          git commit -m "CI: update DB/Stock V/reports + indices"
          git push origin HEAD:main || {
            git pull --rebase --autostash origin main || true
            git push origin HEAD:main || git push --force-with-lease origin HEAD:main
          }
